---
include:
  - board: seeeduino_xiao_ble
    shield: delta_omega_left
    snippet: zmk-usb-logging
  - board: seeeduino_xiao_ble
    shield: delta_omega_right
    snippet: zmk-usb-logging
  - board: seeeduino_xiao_ble
    shield: settings_reset
